name: Wdrożenie projektu na serwerze poprzez FTP
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  web-deploy:
    name: Wdrożenie na FTP
    runs-on: ubuntu-latest
    steps:
    - name: Załadowanie kodu
      uses: actions/checkout@v3
    - name: Synchronizacja plików
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with: 
        server: s1.ct8.pl
        username: ${{secrets.ftp_username}}
        password: ${{secrets.ftp_password}}

  
